name: LostLand of Sirius
author: WEILIN
url: https://weilin111.github.io/myPage/
resume_site: https://weilin111.github.io/myPage/
baseurl: 
description: wuhu
github_username: weilin
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 33
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
defaults:
  - scope:
      path: "ZLG/SU/su"
    values:
      su: true
  - scope:
      path: "ZLG/AA/aa"
    values:
      aa: true
  - scope:
      path: "ZLG/AA/aa02"
    values:
      aa02: true
  - scope:
      path: "ZLG/CA/ca"
    values:
      ca: true
  - scope:
      path: "ZLG/SONG/ss"
    values:
      ss: true
comments :
  gitalk :
    clientID : xxx
    clientSecret : xxx
    repo : 
    owner : 
    admin : 