name: LostLand of Sirius
author: WEILIN
url: https://weilin111.github.io/myPage/
resume_site: https://weilin111.github.io/myPage/
baseurl: 
description: wuhu
github_username: weilin
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 20
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : xxx
    clientSecret : xxx
    repo : 
    owner : 
    admin : 