

MoscowMetroStations = [

    {
        name: "特罗帕廖沃",
        lineNumber: [1],
        pre: {1:null,},
        next: {1:"西南"},
        position:[247,988],
        connect:[],
    },
    {
        name: "西南",
        lineNumber: [1],
        pre: {1:"特罗帕廖沃",},
        next: {1:"维尔纳德斯基大道"},
        position:[276,955],
        connect:[],
    },
    {
        name: "维尔纳德斯基大道",
        lineNumber: [1],
        pre: {1:null,},
        next: {1:"西南"},
        position:[309,929],
        connect:[],
    },
    {
        name: "大学",
        lineNumber: [1],
        pre: {1:null,},
        next: {1:"西南"},
        position:[337,898],
        connect:[],
    },
    {
        name: "麻雀山",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[368,870],
        connect:[],
    },
    {
        name: "运动",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[397,839],
        connect:[],
    },
    {
        name: "伏龙芝",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[426,806],
        connect:[],
    },
    {
        name: "文化公园",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[460,778],
        connect:[],
    },
    {
        name: "克鲁泡特金",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[534,696],
        connect:[],
    },
    {
        name: "列宁图书馆",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[608,627],
        connect:[],
    },
    {
        name: "猎人商行",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[644,587],
        connect:[],
    },
    {
        name: "卢比扬卡",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[697,529],
        connect:[],
    },
    {
        name: "清塘",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[800,509],
        connect:[],
    },
    {
        name: "红门",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[844,462],
        connect:[],
    },
    {
        name: "共青团",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[892,417],
        connect:[],
    },
    {
        name: "红村",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[925,386],
        connect:[],
    },
    {
        name: "索科利尼基",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[953,354],
        connect:[],
    },
    {
        name: "革新广场",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[985,326],
        connect:[],
    },
    {
        name: "切尔基佐沃",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[1011,297],
        connect:[],
    },
    {
        name: "罗科索夫斯基林荫路",
        lineNumber: [1],
        pre: {1:"",},
        next: {1:"西南"},
        position:[1041,264],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "河运码头",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[297,196],
        connect:[],
    },
    {
        name: "水运馆",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[300,220],
        connect:[],
    },
    {
        name: "沃伊科夫",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[329,259],
        connect:[],
    },
    {
        name: "隼鸟",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[357,297],
        connect:[],
    },
    {
        name: "机场",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[387,330],
        connect:[],
    },
    {
        name: "迪纳摩",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[416,357],
        connect:[],
    },
    {
        name: "白俄罗斯",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[445,386],
        connect:[],
    },
    {
        name: "马雅科夫斯基",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[502,442],
        connect:[],
    },
    {
        name: "特维尔",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[549,487],
        connect:[],
    },
    {
        name: "剧院",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[665,606],
        connect:[],
    },
    {
        name: "新库兹涅佐克",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[748,715],
        connect:[],
    },
    {
        name: "帕维列茨",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[824,800],
        connect:[],
    },
    {
        name: "汽车厂",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[899,880],
        connect:[],
    },
    {
        name: "科洛姆纳",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[914,950],
        connect:[],
    },
    {
        name: "卡希拉",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[917,1024],
        connect:[],
    },
    {
        name: "坎捷米尔",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[914,1070],
        connect:[],
    },
    {
        name: "察里芩诺",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[914,1100],
        connect:[],
    },
    {
        name: "核桃",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[914,1132],
        connect:[],
    },
    {
        name: "多莫杰多沃",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[932,1163],
        connect:[],
    },
    {
        name: "红卫兵",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[960,1186],
        connect:[],
    },
    {
        name: "阿拉木图",
        lineNumber: [2],
        pre: {2:"",},
        next: {2:"西南"},
        position:[1021,1200],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "皮亚尼察公路",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,217],
        connect:[],
    },
    {
        name: "米金诺",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,249],
        connect:[],
    },
    {
        name: "沃洛科拉姆斯克",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,277],
        connect:[],
    },
    {
        name: "米亚金宁诺",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,307],
        connect:[],
    },
    {
        name: "斯特罗金诺",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,338],
        connect:[],
    },
    {
        name: "克雷拉兹科耶",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,363],
        connect:[],
    },
    {
        name: "青年",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,398],
        connect:[],
    },
    {
        name: "昆采沃",
        lineNumber: [3,4],
        pre: {3:"",},
        next: {3:"西南"},
        position:[51,427],
        connect:[],
    },
    {
        name: "斯拉夫林荫路",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[104,557],
        connect:[],
    },
    {
        name: "胜利公园",
        lineNumber: [3,8],
        pre: {3:"",},
        next: {3:"西南"},
        position:[163,611],
        connect:[],
    },
    {
        name: "基辅",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[387,624],
        connect:[],
    },
    {
        name: "阿尔巴特",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[567,630],
        connect:[],
    },
    {
        name: "革命广场",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[685,630],
        connect:[],
    },
    {
        name: "库尔斯克",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[896,605],
        connect:[],
    },
    {
        name: "鲍曼",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[941,566],
        connect:[],
    },
    {
        name: "发电厂",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[970,538],
        connect:[],
    },
    {
        name: "谢苗诺夫",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[999,507],
        connect:[],
    },
    {
        name: "游击队",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[1029,478],
        connect:[],
    },
    {
        name: "伊兹迈洛沃",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[1061,448],
        connect:[],
    },
    {
        name: "五一",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[1086,413],
        connect:[],
    },
    {
        name: "晓尔科沃",
        lineNumber: [3],
        pre: {3:"",},
        next: {3:"西南"},
        position:[1120,383],
        connect:[],
    },
   
    // -------------------------------------- //

    {
        name: "昆采沃",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[49,427],
        connect:[],
    },
    {
        name: "少先队",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[92,466],
        connect:[],
    },
    {
        name: "菲利公园",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[119,501],
        connect:[],
    },
    {
        name: "巴格拉季昂",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[150,526],
        connect:[],
    },
    {
        name: "菲利",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[176,560],
        connect:[],
    },
    {
        name: "库图佐夫",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[279,587],
        connect:[],
    },
    {
        name: "学生",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[339,608],
        connect:[],
    },
    {
        name: "基辅",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[406,608],
        connect:[],
    },
    {
        name: "摩尔棱斯克-2",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[454,584],
        connect:[],
    },
    {
        name: "阿尔巴特-2",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[532,584],
        connect:[],
    },
    {
        name: "亚历山大公园",
        lineNumber: [4],
        pre: {4:"",},
        next: {4:"西南"},
        position:[585,608],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "基辅",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[401,647],
        connect:[],
    },
    {
        name: "文化公园",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[454,748],
        connect:[],
    },
    {
        name: "十月",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[623,839],
        connect:[],
    },
    {
        name: "多勃雷宁",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[732,831],
        connect:[],
    },
    {
        name: "帕韦列茨",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[797,801],
        connect:[],
    },
    {
        name: "塔甘卡",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[886,717],
        connect:[],
    },
    {
        name: "库尔斯克",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[916,626],
        connect:[],
    },
    {
        name: "共青团",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[858,416],
        connect:[],
    },
    {
        name: "和平大道",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[778,353],
        connect:[],
    },
    {
        name: "新村庄",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[558,348],
        connect:[],
    },
    {
        name: "红普列斯妮娅",
        lineNumber: [5],
        pre: {5:"",},
        next: {5:"西南"},
        position:[415,493],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "斯亚先涅沃",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[489,1177],
        connect:[],
    },
    {
        name: "亚先涅沃",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[487,1130],
        connect:[],
    },
    {
        name: "暖营",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[487,1099],
        connect:[],
    },
    {
        name: "孔尼科沃",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[487,1070],
        connect:[],
    },
    {
        name: "新别亚耶沃",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[487,1039],
        connect:[],
    },
    {
        name: "卡卢加",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[487,1010],
        connect:[],
    },
    {
        name: "新稠李",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[492,974],
        connect:[],
    },
    {
        name: "工会",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[518,946],
        connect:[],
    },
    {
        name: "科学院",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[549,917],
        connect:[],
    },
    {
        name: "列宁大道",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[579,884],
        connect:[],
    },
    {
        name: "沙博罗夫卡",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[608,856],
        connect:[],
    },
    {
        name: "十月",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[643,821],
        connect:[],
    },
    {
        name: "特列季亚科夫",
        lineNumber: [6,8],
        pre: {6:"",},
        next: {6:"西南"},
        position:[728,734],
        connect:[],
    },
    {
        name: "中国城",
        lineNumber: [6,7],
        pre: {6:"",},
        next: {6:"西南"},
        position:[781,649],
        connect:[],
    },
    {
        name: "屠格涅夫",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[781,488],
        connect:[],
    },
    {
        name: "苏哈列夫",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[781,394],
        connect:[],
    },
    {
        name: "和平大道",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,329],
        connect:[],
    },
    {
        name: "里加",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,286],
        connect:[],
    },
    {
        name: "阿列克谢",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,257],
        connect:[],
    },
    {
        name: "国经成就展",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,227],
        connect:[],
    },
    {
        name: "植物园",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,199],
        connect:[],
    },
    {
        name: "斯维布洛沃",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,166],
        connect:[],
    },
    {
        name: "巴布什金",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,137],
        connect:[],
    },
    {
        name: "梅德维德科沃",
        lineNumber: [6],
        pre: {6:"",},
        next: {6:"西南"},
        position:[798,107],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "滑翔机",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[243,201],
        connect:[],
    },
    {
        name: "斯霍德妮娅",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[243,231],
        connect:[],
    },
    {
        name: "图申诺",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[243,263],
        connect:[],
    },
    {
        name: "斯巴达",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[243,291],
        connect:[],
    },
    {
        name: "休金诺",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[253,323],
        connect:[],
    },
    {
        name: "十月平原",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[285,354],
        connect:[],
    },
    {
        name: "波列扎耶夫",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[310,383],
        connect:[],
    },
    {
        name: "别戈沃伊",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[344,410],
        connect:[],
    },
    {
        name: "1905大街",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[374,442],
        connect:[],
    },
    {
        name: "路障",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[434,469],
        connect:[],
    },
    {
        name: "普希金",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[566,469],
        connect:[],
    },
    {
        name: "库兹涅佐克桥",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[704,499],
        connect:[],
    },
    {
        name: "中国城",
        lineNumber: [7,6],
        pre: {7:"",},
        next: {7:"西南"},
        position:[781,646],
        connect:[],
    },
    {
        name: "塔甘卡",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[883,754],
        connect:[],
    },
    {
        name: "无产阶级",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[960,830],
        connect:[],
    },
    {
        name: "伏尔加格勒大道",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1011,880],
        connect:[],
    },
    {
        name: "纺织工",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1040,911],
        connect:[],
    },
    {
        name: "库济明基",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1071,941],
        connect:[],
    },
    {
        name: "梁赞大道",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1101,970],
        connect:[],
    },
    {
        name: "维欣诺",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1110,993],
        connect:[],
    },
    {
        name: "莱蒙托夫大道",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1110,1026],
        connect:[],
    },
    {
        name: "茹列宾诺",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1110,1056],
        connect:[],
    },
    {
        name: "科捷利尼基",
        lineNumber: [7],
        pre: {7:"",},
        next: {7:"西南"},
        position:[1110,1083],
        connect:[],
    },


    // -------------------------------------- //

    {
        name: "特列季亚科夫",
        lineNumber: [8,6],
        pre: {8:"",},
        next: {8:"西南"},
        position:[728,736],
        connect:[],
    },
    {
        name: "马克思主义者",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[901,736],
        connect:[],
    },
    {
        name: "伊里奇广场",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[1006,732],
        connect:[],
    },
    {
        name: "航空发动机",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[1038,701],
        connect:[],
    },
    {
        name: "热情公路",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[1071,671],
        connect:[],
    },
    {
        name: "佩罗沃",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[1101,641],
        connect:[],
    },
    {
        name: "新吉列耶沃",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[1127,611],
        connect:[],
    },
    {
        name: "新科辛诺",
        lineNumber: [8],
        pre: {8:"",},
        next: {8:"西南"},
        position:[1159,578],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "伏努科沃",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[49,1046],
        connect:[],
    },
    {
        name: "佩赫金诺",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[49,1016],
        connect:[],
    },
    {
        name: "拉斯卡佐夫卡",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[49,986],
        connect:[],
    },
    {
        name: "新佩列杰尔金诺",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[49,956],
        connect:[],
    },
    {
        name: "博罗夫斯克公路",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[79,926],
        connect:[],
    },
    {
        name: "太阳",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[97,893],
        connect:[],
    },
    {
        name: "戈沃罗沃",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[115,860],
        connect:[],
    },
    {
        name: "湖区",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[133,827],
        connect:[],
    },
    {
        name: "米丘林大道",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[151,794],
        connect:[],
    },
    {
        name: "拉缅基",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[169,761],
        connect:[],
    },
    {
        name: "罗蒙诺索夫大道",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[169,715],
        connect:[],
    },
    {
        name: "明斯克",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[169,660],
        connect:[],
    },
    {
        name: "胜利公园",
        lineNumber: ["8A"],
        pre: {"8A":"",},
        next: {"8A":"西南"},
        position:[167,611],
        connect:[],
    },
    // -------------------------------------- //

    {
        name: "德米特里·顿斯科伊林荫路",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[603,1233],
        connect:[],
    },
    {
        name: "安宁诺",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[636,1202],
        connect:[],
    },
    {
        name: "扬格利院士街",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[666,1171],
        connect:[],
    },
    {
        name: "布拉格",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[695,1141],
        connect:[],
    },
    {
        name: "南区",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[722,1114],
        connect:[],
    },
    {
        name: "切尔坦诺沃",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,1082],
        connect:[],
    },
    {
        name: "塞瓦斯托波尔",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,1025],
        connect:[],
    },
    {
        name: "纳西莫夫大道",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,991],
        connect:[],
    },
    {
        name: "纳戈尔诺",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,963],
        connect:[],
    },
    {
        name: "纳加金诺",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,932],
        connect:[],
    },
    {
        name: "图拉",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,900],
        connect:[],
    },
    {
        name: "谢尔普霍夫",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[732,861],
        connect:[],
    },
    {
        name: "林地",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[647,763],
        connect:[],
    },
    {
        name: "博罗维茨基",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[586,647],
        connect:[],
    },
    {
        name: "契诃夫",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[586,486],
        connect:[],
    },
    {
        name: "七彩林荫路",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[648,412],
        connect:[],
    },
    {
        name: "门捷列夫",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[556,315],
        connect:[],
    },
    {
        name: "萨维奥洛沃",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[545,275],
        connect:[],
    },
    {
        name: "德米特罗夫",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[546,237],
        connect:[],
    },
    {
        name: "季米里亚泽夫",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[545,207],
        connect:[],
    },
    {
        name: "彼得罗夫-拉祖莫夫",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[544,175],
        connect:[],
    },
    {
        name: "弗拉德金诺",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[545,147],
        connect:[],
    },
    {
        name: "愉悦",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[545,115],
        connect:[],
    },
    {
        name: "碧比列沃",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[545,84],
        connect:[],
    },
    {
        name: "阿尔图菲耶沃",
        lineNumber: [9],
        pre: {9:"",},
        next: {9:"西南"},
        position:[545,58],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "贾布里科沃",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1208],
        connect:[],
    },
    {
        name: "希皮洛夫",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1167],
        connect:[],
    },
    {
        name: "博里索沃",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1139],
        connect:[],
    },
    {
        name: "马里诺",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1109],
        connect:[],
    },
    {
        name: "布拉迪斯拉发",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1087],
        connect:[],
    },
    {
        name: "柳布林诺",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1049],
        connect:[],
    },
    {
        name: "伏尔加",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,1018],
        connect:[],
    },
    {
        name: "印刷工",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,988],
        connect:[],
    },
    {
        name: "科茹霍夫",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,959],
        connect:[],
    },
    {
        name: "橡木",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,927],
        connect:[],
    },
    {
        name: "农民哨岗",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,809],
        connect:[],
    },
    {
        name: "罗马",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[984,753],
        connect:[],
    },
    {
        name: "契卡沃夫",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[897,644],
        connect:[],
    },
    {
        name: "斯利坚斯克林荫路",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[777,526],
        connect:[],
    },
    {
        name: "引水管",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[678,414],
        connect:[],
    },
    {
        name: "陀思妥耶夫斯基",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[677,297],
        connect:[],
    },
    {
        name: "玛琳娜灌林",
        lineNumber: [10],
        pre: {10:"",},
        next: {10:"西南"},
        position:[677,267],
        connect:[],
    },

    // -------------------------------------- //

    {
        name: "卡霍夫卡",
        lineNumber: [11],
        pre: {11:"",},
        next: {11:"西南"},
        position:[758,1027],
        connect:[],
    },
    {
        name: "华沙",
        lineNumber: [11],
        pre: {11:"",},
        next: {11:"西南"},
        position:[835,1027],
        connect:[],
    },
    {
        name: "卡希拉",
        lineNumber: [11,2],
        pre: {11:"",},
        next: {11:"西南"},
        position:[918,1027],
        connect:[],
    },
    // -------------------------------------- //

    {
        name: "蒲宁路",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[324,1270],
        connect:[],
    },
    {
        name: "戈尔恰科夫街",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[405,1270],
        connect:[],
    },
    {
        name: "乌沙科夫",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[484,1270],
        connect:[],
    },
    {
        name: "斯科别列夫街",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[560,1270],
        connect:[],
    },
    {
        name: "旧卡恰洛沃街",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[584,1253],
        connect:[],
    },
    {
        name: "森林公园",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[552,1215],
        connect:[],
    },
    {
        name: "比察公园",
        lineNumber: [12],
        pre: {12:"",},
        next: {12:"西南"},
        position:[513,1173],
        connect:[],
    },
    // -------------------------------------- //

    {
        name: "基辅",
        lineNumber: [13],
        pre: {5:"",},
        next: {5:"西南"},
        position:[401,647],
        connect:[],
    },
    // -------------------------------------- //

    {
        name: "基辅",
        lineNumber: [14],
        pre: {5:"",},
        next: {5:"西南"},
        position:[401,647],
        connect:[],
    },
    // -------------------------------------- //

    {
        name: "基辅",
        lineNumber: [15],
        pre: {5:"",},
        next: {5:"西南"},
        position:[401,647],
        connect:[],
    },
    // -------------------------------------- //

    {
        name: "基辅",
        lineNumber: [16],
        pre: {5:"",},
        next: {5:"西南"},
        position:[401,647],
        connect:[],
    },
    


]


