# Generated by Django 3.2 on 2021-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visited_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
