# Generated by Django 3.2 on 2021-04-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0002_visited_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited_number',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
