# Generated by Django 3.2 on 2021-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0004_rename_number_visited_number_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited_number',
            name='visit_time',
            field=models.CharField(max_length=30),
        ),
    ]
