# Generated by Django 3.2 on 2021-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDB', '0005_alter_visited_number_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visited_number',
            name='total_visited_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
